---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files

      - id: mixed-line-ending
        alias: check-line-endings
        name: check-line-endings
        args: ['--fix=no']

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint

  - repo: https://github.com/jmknoble/json-indent
    rev: v2.5.1
    hooks:
      - id: json-indent
        args: ['--newlines=linux']

  - repo: https://github.com/jmknoble/markdown-toc
    rev: v0.2.3
    hooks:
      - id: markdown-toc
        args: ['--heading-level', '2', '--skip-level', '1']

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        args:
          - '--application-directories=hooks'
          - '--exclude=(docs?|examples?|tests?|utils?|\{\{cookiecutter\.[^}]*\}\})/.*\.py'

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        alias: black-check
        name: black-check
        args: ['--check']
        stages: [manual]

      - id: black
        alias: black-diff
        name: black-diff
        args: ['--check', '--diff']
        stages: [manual]

      - id: black
        alias: black-reformat
        name: black-reformat
        args: []

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/prospector
    rev: 1.3.1
    hooks:
      - id: prospector
        args: ['--profile=prospector_profile.yml']
        # add any needed Python package requirements here
        additional_dependencies:
          - 'pytest>=4.6'
          - 'argcomplete >= 1.12.3'

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: (__init__|setup|(docs?|examples?|tests?|utils?)/.*)\.py$
...
