default_context:
  category: general
  description: Opinionated but flexible Python virtual environment tool
  git_base_url: https://github.com/jmknoble
  git_group: jmknoble
  git_project: python-venv
  git_url: https://github.com/jmknoble/python-venv
  package_name: python_venv
  project_name: python-venv
  project_type: python
  team_email: jmknoble@pobox.com
  team_name: jmknoble
  title: python-venv
  version: 0.10.0
