"""Provide package constants."""

import os.path

STATUS_SUCCESS = 0
STATUS_FAILURE = 1
STATUS_HELP = 2

PYTHON = "python3"
PYTHON_VERSION_REGEX = r"^[0-9]+(\.[0-9]+){0,2}"  # Must start with X, X.Y, or X.Y.Z

DEFAULT_VENVS_DIR = os.path.join("~", ".venvs")

ENV_VAR_USE_PYTHON = "PYTHON_VENV_USE_PYTHON"
ENV_VAR_USE_PYTHON_VERSION = "PYTHON_VENV_USE_PYTHON_VERSION"
ENV_VAR_VENVS_DIR = "PYTHON_VENV_VENVS_DIR"

CONDA = "conda"
PYENV = "pyenv"
PYENV_VERSION = "PYENV_VERSION"
VENV_DIR = ".venv"
DEV_SUFFIX = "-dev"

MESSAGE_PREFIX = "==> "

DIST_DIR = "dist"
ENV_DIR_PLACEHOLDER = "<ENV_DIR>"

ENV_TYPE_VENV = "venv"
ENV_TYPE_NAMED_VENV = "named-venv"
ENV_TYPE_PYENV = "pyenv"
ENV_TYPE_CONDA = "conda"

ENV_TYPES = [
    ENV_TYPE_VENV,
    ENV_TYPE_NAMED_VENV,
    ENV_TYPE_PYENV,
    ENV_TYPE_CONDA,
]

ENV_TYPES_NAMED = [
    ENV_TYPE_NAMED_VENV,
    ENV_TYPE_PYENV,
    ENV_TYPE_CONDA,
]

ENV_TYPES_VERSIONED = [
    ENV_TYPE_PYENV,
    ENV_TYPE_CONDA,
]

ENV_TYPES_VERSIONED_STRICT = [
    ENV_TYPE_CONDA,
]

FROM_FILES = "files"
FROM_PACKAGES = "packages"
FROM_COMMANDS = "commands"
FROM_BDIST_WHEEL = "bdist_wheel"
FROM_PIP_ARGS = "pip_args"
